-- ============================================================================
-- Migration: 0002_seed_exercises.sql
-- Real animated gym workout GIFs served locally from /gifs/*.gif
-- Total Curated Exercises: 68
-- Target: Cloudflare D1 (SQLite)
-- ============================================================================

DELETE FROM exercises;

INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_barbell_bench_press', 'پرس سینه با هالتر', 'Barbell Bench Press', 'chest', 'سینه', 'barbell', 'هالتر', 'عضله سینه‌ای بزرگ (پکتورالیس ماژور)', 'پشت بازو (سه‌سر بازویی)، دلتوئید قدامی', '۱. روی نیمکت تخت دراز بکشید و پاها را محکم روی زمین بگذارید.
۲. هالتر را با فاصله‌ای کمی بازتر از عرض شانه بگیرید.
۳. میله را با کنترل کامل تا وسط قفسه سینه پایین بیاورید.
۴. با انقباض عضلات سینه میله را با قدرت به بالا پرس کنید.', '/gifs/0025.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_incline_barbell_bench_press', 'پرس بالاسینه با هالتر', 'Incline Barbell Bench Press', 'chest', 'سینه', 'barbell', 'هالتر', 'بخش بالایی سینه (سر کلاویکولار)', 'دلتوئید جلویی، پشت بازو', '۱. شیب نیمکت را روی ۳۰ الی ۴۵ درجه تنظیم کنید.
۲. هالتر را اندازه عرض شانه بگیرید و با کنترل تا بالای ترقوه پایین بیاورید.
۳. میله را مستقیم به سمت بالا پرس کنید.', '/gifs/0047.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_decline_barbell_bench_press', 'پرس زیرسینه با هالتر', 'Decline Barbell Bench Press', 'chest', 'سینه', 'barbell', 'هالتر', 'بخش زیرین سینه (سر استرنال)', 'پشت بازو، بخش تحتانی سینه', '۱. روی نیمکت شیب‌منفی قرار بگیرید و پاها را محکم در گیره قفل کنید.
۲. هالتر را تا خط زیرین سینه پایین آورده و با تمرکز بالا ببرید.', '/gifs/0033.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_dumbbell_bench_press', 'پرس سینه با دمبل', 'Dumbbell Bench Press', 'chest', 'سینه', 'dumbbell', 'دمبل', 'عضله سینه‌ای بزرگ و افزایش تعادل عضلانی', 'پشت بازو، تثبیت‌کننده‌های شانه', '۱. دمبل‌ها را با کمک زانوها روی سینه هدایت کرده و دراز بکشید.
۲. دمبل‌ها را تا کنار سینه با کشش مناسب پایین بیاورید.
۳. به صورت موازی به بالا فشار داده و در اوج انقباض مکث کنید.', '/gifs/0289.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_incline_dumbbell_press', 'پرس بالاسینه با دمبل', 'Incline Dumbbell Press', 'chest', 'سینه', 'dumbbell', 'دمبل', 'بخش بالایی عضلات سینه', 'سرشانه قدامی، پشت بازو', '۱. روی نیمکت با زاویه ۳۰ تا ۴۵ درجه بنشینید.
۲. دمبل‌ها را با هدایت آرنج‌ها به سمت بالا ببرید.
۳. در بالای دامنه از برخورد شدید دمبل‌ها به هم خودداری کنید.', '/gifs/0314.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_dumbbell_fly', 'قفسه سینه با دمبل (فلای)', 'Dumbbell Chest Fly', 'chest', 'سینه', 'dumbbell', 'دمبل', 'عضلات سینه با تاکید بر کشش عرضی', 'دلتوئید قدامی', '۱. روی نیمکت خوابیده و دمبل‌ها را با آرنج‌های کمی خمیده به طرفین باز کنید.
۲. تا ایجاد کشش مطلوب در سینه پایین بروید.
۳. مثل در آغوش گرفتن یک تنه درخت دست‌ها را به هم نزدیک کنید.', '/gifs/0308.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_incline_dumbbell_fly', 'قفسه بالاسینه با دمبل', 'Incline Dumbbell Fly', 'chest', 'سینه', 'dumbbell', 'دمبل', 'بخش فوقانی عضلات سینه', 'شانه قدامی', '۱. نیمکت را شیب‌دار کرده و دمبل‌ها را با قوس ملایم آرنج باز کنید.
۲. در اوج کشش مکث کرده و به سمت بالای سینه جمع کنید.', '/gifs/0319.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_cable_crossover', 'کراس اور با سیم‌کش از بالا', 'High Cable Crossover', 'chest', 'سینه', 'cable', 'سیم‌کش', 'خط وسط و بخش تحتانی سینه', 'دلتوئید قدامی', '۱. دسته‌های سیم‌کش را در بالاترین ارتفاع قرار دهید.
۲. یک گام به جلو بگذارید و دست‌ها را به سمت جلوی ناف و پایین فشرده کنید.', '/gifs/0179.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_cable_low_fly', 'کراس اور از پایین با سیم‌کش', 'Low Cable Crossover', 'chest', 'سینه', 'cable', 'سیم‌کش', 'بخش بالایی و خط داخلی سینه', 'دلتوئید قدامی', '۱. دسته‌ها را در پایین‌ترین قرقره قرار دهید.
۲. دست‌ها را با قوس ملایم به سمت بالای سینه و روبروی چانه بالا بکشید.', '/gifs/0197.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_push_up', 'شنا سوئدی استاندارد', 'Standard Push-Up', 'chest', 'سینه', 'bodyweight', 'وزن بدن', 'عضله سینه و استقامت کلی بالاتنه', 'پشت بازو، عضلات مرکزی (Core)', '۱. دست‌ها را به اندازه عرض شانه روی زمین بگذارید.
۲. بدن را در یک خط مستقیم نگه داشته و تا نزدیک زمین پایین بیایید.
۳. با قدرت به بالا برگردید.', '/gifs/0662.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_decline_push_up', 'شنا سوئدی شیب منفی (پا بالا)', 'Decline Push-Up', 'chest', 'سینه', 'bodyweight', 'وزن بدن', 'بخش بالایی سینه و سرشانه‌ها', 'پشت بازو، میان‌تنه', '۱. پاها را روی نیمکت یا سکوی بلند قرار دهید.
۲. دست‌ها روی زمین و سینه را با تمرکز تا سطح زمین پایین بیاورید.', '/gifs/0279.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_chest_dip', 'دیپ پارالل سینه', 'Chest Dip', 'chest', 'سینه', 'bodyweight', 'وزن بدن', 'بخش تحتانی سینه و خط زیر سینه', 'پشت بازو، شانه قدامی', '۱. میله‌های پارالل را گرفته و بالاتنه را ۳۰ درجه به جلو متمایل کنید.
۲. تا زاویه ۹۰ درجه آرنج پایین رفته و سپس به بالا فشار دهید.', '/gifs/0251.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_machine_chest_press', 'پرس سینه با دستگاه', 'Machine Chest Press', 'chest', 'سینه', 'machine', 'دستگاه', 'کل عضلات سینه با حداکثر ایمنی مفصلی', 'پشت بازو', '۱. ارتفاع نشیمن را تنظیم کنید تا دسته‌ها در خط میانه سینه باشند.
۲. با بازدم دسته‌ها را به جلو هدایت کرده و با کنترل بازگردانید.', '/gifs/0022.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_barbell_deadlift', 'ددلیفت کلاسیک با هالتر', 'Barbell Deadlift', 'back', 'پشت و زیربغل', 'barbell', 'هالتر', 'فیله کمر، عضلات پشتی بزرگ (لاتیسیموس)', 'همسترینگ، باسن، ساعد', '۱. روبروی هالتر بایستید و پاها به عرض لگن باشد.
۲. با ستون فقرات کاملاً خنثی و بدون قوز میله را بگیرید.
۳. با فشار پاشنه‌ها و باز کردن لگن وزنه را به بالا هدایت کنید.', '/gifs/0032.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_bent_over_barbell_row', 'زیربغل هالتر خم', 'Bent-Over Barbell Row', 'back', 'پشت و زیربغل', 'barbell', 'هالتر', 'عضلات متوازی‌الاضلاع (رومبوئید) و لت‌ها', 'جلو بازو، فیله کمر', '۱. بالاتنه را با زاویه ۴۵ درجه خم کرده و زانوها را اندکی خم کنید.
۲. میله را به سمت زیر ناف بکشید و کتف‌ها را در اوج به هم فشار دهید.', '/gifs/0027.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_one_arm_dumbbell_row', 'زیربغل دمبل تک‌خم (اره‌ای)', 'One-Arm Dumbbell Row', 'back', 'پشت و زیربغل', 'dumbbell', 'دمبل', 'عضله پشتی بزرگ یک‌طرفه و افزایش تقارن', 'جلوبازو، دلتوئید خلفی', '۱. یک زانو و دست را روی نیمکت قرار داده و پشت را صاف کنید.
۲. دمبل را با هدایت آرنج به سمت پهلو بالا بکشید و آرام بازگردانید.', '/gifs/0292.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_lat_pulldown', 'زیربغل سیم‌کش لت از جلو', 'Cable Lat Pulldown', 'back', 'پشت و زیربغل', 'cable', 'سیم‌کش', 'عضله پشتی بزرگ و پهن کردن بالاتنه', 'جلو بازو، بخش میانی پشت', '۱. ران‌ها را زیر بالشتک دستگاه قفل کنید و میله را با دستان باز بگیرید.
۲. میله را به سمت بالای سینه پایین بکشید و کتف‌ها را منقبض کنید.', '/gifs/0150.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_close_grip_lat_pulldown', 'زیربغل سیم‌کش لت دست جمع', 'Close-Grip Lat Pulldown', 'back', 'پشت و زیربغل', 'cable', 'سیم‌کش', 'بخش تحتانی عضلات زیربغل', 'جلو بازو، ساعد', '۱. از دسته V شکل (دست جمع) استفاده کنید.
۲. با تکیه ملایم به عقب، دسته را تا وسط سینه پایین بکشید.', '/gifs/0210.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_seated_cable_row', 'زیربغل قایقی با سیم‌کش', 'Seated Cable Row', 'back', 'پشت و زیربغل', 'cable', 'سیم‌کش', 'ضخامت بخش میانی عضلات پشت', 'جلو بازو، دلتوئید خلفی', '۱. پاها را روی تکیه‌گاه گذاشته و پشت را صاف نگه دارید.
۲. دسته را به سمت شکم بکشید و شانه‌ها را به عقب رول کنید.', '/gifs/0198.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_wide_pull_up', 'بارفیکس دست باز', 'Wide-Grip Pull-Up', 'back', 'پشت و زیربغل', 'bodyweight', 'وزن بدن', 'عضلات پشتی بزرگ و بالاتنه V-Shape', 'جلو بازو، فیله کمر', '۱. میله را با دست‌های بازتر از عرض شانه بگیرید.
۲. بدن را بالا بکشید تا چانه بالای میله قرار گیرد و با کنترل پایین بیایید.', '/gifs/0652.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_chin_up', 'بارفیکس دست جمع مچ برعکس (چین‌آپ)', 'Chin-Up', 'back', 'پشت و زیربغل', 'bodyweight', 'وزن بدن', 'عضلات زیربغل و جلو بازو', 'ساعد، میان‌تنه', '۱. میله را با کف دستان رو به خود بگیرید.
۲. با فشار همزمان زیربغل و جلوبازو بالا رفته و مکث کنید.', '/gifs/0253.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_tbar_row', 'زیربغل تی‌بار با دستگاه', 'Lever T-Bar Row', 'back', 'پشت و زیربغل', 'machine', 'دستگاه', 'بخش میانی و فوقانی پشت', 'جلو بازو، فیله', '۱. روی دستگاه قرار گرفته و دسته‌ها را محکم بگیرید.
۲. وزنه را به سمت سینه بکشید و در اوج دامنه انقباض ایجاد کنید.', '/gifs/1349.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_straight_arm_pulldown', 'پلاور سیم‌کش ایستاده (دست صاف)', 'Straight-Arm Cable Pulldown', 'back', 'پشت و زیربغل', 'cable', 'سیم‌کش', 'ایزولاسیون کامل عضله پشتی بزرگ', 'پشت بازو، سر سینه', '۱. روبروی قرقره بالا بایستید و میله را با بازوهای صاف نگه دارید.
۲. بدون خم کردن آرنج‌ها، میله را با انقباض زیربغل تا ران‌ها پایین بیاورید.', '/gifs/0238.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_hyperextension', 'فیله کمر روی نیمکت ۴۵ درجه', 'Back Hyperextension', 'back', 'پشت و زیربغل', 'bodyweight', 'وزن بدن', 'عضلات راست‌کننده ستون فقرات (فیله کمر)', 'باسن، همسترینگ', '۱. روی نیمکت فیله قرار بگیرید و دست‌ها را روی سینه ضربدری بگیرید.
۲. به آرامی از ناحیه کمر خم شده و سپس با انقباض کمر صاف شوید.', '/gifs/0489.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_barbell_shrug', 'شراگ هالتر (عضلات کول)', 'Barbell Shrug', 'back', 'پشت و زیربغل', 'barbell', 'هالتر', 'عضله ذوزنقه‌ای بالایی (کول)', 'ساعد، گردن', '۱. هالتر را جلوی ران‌ها نگه دارید و شانه‌ها را مستقیماً به سمت گوش‌ها بالا بکشید.
۲. از چرخاندن شانه‌ها خودداری کرده و در اوج ۲ ثانیه مکث کنید.', '/gifs/0095.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_dumbbell_shrug', 'شراگ با دمبل', 'Dumbbell Shrug', 'back', 'پشت و زیربغل', 'dumbbell', 'دمبل', 'عضلات کول و ذوزنقه‌ای', 'ساعد', '۱. دمبل‌ها را در کنار پهلوها نگه دارید.
۲. شانه‌ها را فقط در جهت عمودی بالا ببرید و به آرامی پایین بیاورید.', '/gifs/0411.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_barbell_squat', 'اسکوات پا با هالتر از پشت', 'Barbell Back Squat', 'legs', 'پا', 'barbell', 'هالتر', 'عضلات چهارسر ران و سرینی (باسن)', 'همسترینگ، ساق، عضلات مرکزی', '۱. هالتر را روی کول قرار داده و پاها را به اندازه عرض شانه باز کنید.
۲. با عقب دادن لگن تا موازی شدن ران‌ها با زمین بنشینید.
۳. با هدایت فشار به پاشنه به حالت ایستاده برگردید.', '/gifs/0043.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_barbell_front_squat', 'اسکوات از جلو با هالتر', 'Barbell Front Squat', 'legs', 'پا', 'barbell', 'هالتر', 'تمرکز مستقیم بر چهارسر ران و حفظ قامت', 'عضلات شکم و کر', '۱. هالتر را روی بخش جلویی شانه‌ها و ترقوه مهار کنید.
۲. بالاتنه را کاملاً عمود نگه داشته و اسکوات بروید.', '/gifs/0042.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_leg_press', 'پرس پا با دستگاه ۴۵ درجه', 'Leg Press Machine', 'legs', 'پا', 'machine', 'دستگاه', 'چهارسر ران و عضلات سرینی', 'همسترینگ، ساق', '۱. کمر را به صندلی بچسبانید و پاها را وسط صفحه بگذارید.
۲. وزنه را تا زاویه ۹۰ درجه زانو پایین آورده و بدون قفل مفصل به بالا برانید.', '/gifs/0585.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_romanian_deadlift_barbell', 'ددلیفت رومانیایی با هالتر (RDL)', 'Romanian Barbell Deadlift', 'legs', 'پا', 'barbell', 'هالتر', 'عضلات همسترینگ (پشت پا) و سرینی', 'فیله کمر', '۱. با زانوهای کمی خم و پشت صاف، با عقب دادن باسن خم شوید.
۲. میله را تا زیر زانو پایین برده و با انقباض همسترینگ صاف شوید.', '/gifs/0085.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_romanian_deadlift_dumbbell', 'ددلیفت رومانیایی با دمبل', 'Romanian Dumbbell Deadlift', 'legs', 'پا', 'dumbbell', 'دمبل', 'همسترینگ و فرم‌دهی باسن', 'فیله کمر', '۱. دمبل‌ها را جلوی ران نگه دارید و با لولای لگن خم شوید تا کشش پشت پا احساس شود.', '/gifs/0380.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_dumbbell_walking_lunge', 'لانج راه‌رفتنی با دمبل', 'Dumbbell Walking Lunge', 'legs', 'پا', 'dumbbell', 'دمبل', 'چهارسر ران، باسن و تعادل یک‌طرفه', 'ساق، میان‌تنه', '۱. یک گام بلند به جلو بردارید و زانوی عقب را به زمین نزدیک کنید.
۲. با فشار پای جلو گام بعدی را بردارید.', '/gifs/0367.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_leg_extension', 'جلو پا با دستگاه (اکستنشن)', 'Leg Extension Machine', 'legs', 'پا', 'machine', 'دستگاه', 'ایزولاسیون کامل عضله چهارسر ران', 'تاندون کشکک', '۱. ساق را پشت بالشتک قرار داده و پا را تا صاف شدن زانو بالا بیاورید.
۲. یک ثانیه در اوج منقبض کنید و آرام پایین بیاورید.', '/gifs/0588.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_lying_leg_curl', 'پشت پا خوابیده با دستگاه (لگ کرل)', 'Lying Leg Curl Machine', 'legs', 'پا', 'machine', 'دستگاه', 'عضلات دو سر رانی و همسترینگ', 'ساق پا', '۱. روی شکم دراز بکشید و بالشتک را پشت مچ پا مهار کنید.
۲. پاها را به سمت باسن جمع کرده و آرام رها کنید.', '/gifs/0599.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_standing_calf_raise', 'ساق پا ایستاده با دستگاه', 'Standing Calf Raise', 'legs', 'پا', 'machine', 'دستگاه', 'عضله دوقلو ساق (گاستروکنمیوس)', 'سولئوس (نعلی)', '۱. پنجه‌ها روی لبه سکو و پاشنه‌ها آزاد باشد.
۲. پاشنه را کاملاً پایین برده و سپس با نهایت توان روی پنجه بلند شوید.', '/gifs/0772.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_seated_calf_raise', 'ساق پا نشسته با هالتر/دستگاه', 'Seated Calf Raise', 'legs', 'پا', 'barbell', 'هالتر', 'عضله نعلی ساق (سولئوس)', 'مچ پا', '۱. در حالت نشسته وزنه را روی زانوها مهار کنید.
۲. با انقباض ساق، پاشنه‌ها را بالا بیاورید.', '/gifs/0088.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_bulgarian_split_squat', 'اسکوات بلغاری با دمبل', 'Bulgarian Split Squat', 'legs', 'پا', 'dumbbell', 'دمبل', 'عضلات باسن و چهارسر تک‌پا', 'همسترینگ', '۱. پای عقب را روی نیمکت قرار داده و با پای جلو اسکوات عمیق اجرا کنید.', '/gifs/0284.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_goblet_squat', 'گابلت اسکوات با دمبل', 'Goblet Squat', 'legs', 'پا', 'dumbbell', 'دمبل', 'چهارسر ران و بهبود انعطاف‌پذیری لگن', 'عضلات شکم و بازو', '۱. یک دمبل را عمودی جلوی سینه نگه دارید و عمیق بنشینید.', '/gifs/0311.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_overhead_press', 'پرس سرشانه هالتر نظامی ایستاده (OHP)', 'Standing Barbell Military Press', 'shoulders', 'سرشانه', 'barbell', 'هالتر', 'دلتوئید قدامی و میانی', 'پشت بازو، عضلات مرکزی', '۱. میله را در سطح ترقوه نگه دارید.
۲. با منقبض کردن شکم و باسن میله را مستقیم بالای سر ببرید.', '/gifs/0091.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_seated_dumbbell_shoulder_press', 'پرس سرشانه با دمبل نشسته', 'Seated Dumbbell Shoulder Press', 'shoulders', 'سرشانه', 'dumbbell', 'دمبل', 'دلتوئید قدامی و پهن کردن سرشانه', 'پشت بازو', '۱. روی نیمکت با پشتی عمودی بنشینید.
۲. دمبل‌ها را از کنار گوش‌ها به سمت بالا پرس کنید.', '/gifs/0405.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_dumbbell_lateral_raise', 'نشر از جانب با دمبل', 'Dumbbell Lateral Raise', 'shoulders', 'سرشانه', 'dumbbell', 'دمبل', 'دلتوئید جانبی (بخش میانی شانه)', 'کول (تراپزیوس)', '۱. دمبل‌ها را کنار ران‌ها نگه داشته و بدون تاب دادن تنه تا ارتفاع شانه بالا بیاورید.', '/gifs/0334.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_cable_lateral_raise', 'نشر جانب با سیم‌کش تک‌دست', 'Cable Lateral Raise', 'shoulders', 'سرشانه', 'cable', 'سیم‌کش', 'تنش پیوسته بر دلتوئید جانبی', 'سرشانه میانی', '۱. سیم‌کش را در پایین‌ترین نقطه بگذارید و دست را تا خط شانه به طرفین بالا بیاورید.', '/gifs/0188.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_dumbbell_front_raise', 'نشر جلو با دمبل جفت', 'Dumbbell Front Raise', 'shoulders', 'سرشانه', 'dumbbell', 'دمبل', 'دلتوئید قدامی (جلوی شانه)', 'بخش بالایی سینه', '۱. دمبل‌ها را تا ارتفاع چشم بالا آورده و با کنترل پایین ببرید.', '/gifs/0310.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_barbell_front_raise', 'نشر جلو با هالتر', 'Barbell Front Raise', 'shoulders', 'سرشانه', 'barbell', 'هالتر', 'دلتوئید قدامی', 'سینه فوقانی', '۱. هالتر را با دستان به عرض شانه تا ارتفاع دید چشم بالا بکشید.', '/gifs/0041.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_cable_face_pull', 'فیس‌پول با طناب سیم‌کش', 'Cable Face Pull', 'shoulders', 'سرشانه', 'cable', 'سیم‌کش', 'دلتوئید خلفی (پشت سرشانه) و سلامت روتاتور کاف', 'بخش بالایی پشت', '۱. طناب را در سطح پیشانی تنظیم کرده و دو سر طناب را به سمت گوش‌ها بکشید.', '/gifs/0184.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_dumbbell_rear_delt_fly', 'نشر خم دمبل (دلتوئید خلفی)', 'Dumbbell Rear Delt Fly', 'shoulders', 'سرشانه', 'dumbbell', 'دمبل', 'بخش پشتی سرشانه', 'عضلات رومبوئید', '۱. بالاتنه را خم کرده و دمبل‌ها را به طرفین مثل بال پرنده باز کنید.', '/gifs/0377.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_arnold_press', 'پرس سرشانه آرنولدی با دمبل', 'Arnold Dumbbell Press', 'shoulders', 'سرشانه', 'dumbbell', 'دمبل', 'درگیری همزمان سرشانه قدامی و جانبی', 'پشت بازو', '۱. حرکت را با مچ‌های رو به بدن آغاز کرده و همزمان با بالا بردن مچ‌ها را به بیرون بچرخانید.', '/gifs/0013.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_barbell_bicep_curl', 'جلو بازو با هالتر صاف ایستاده', 'Barbell Bicep Curl', 'arms', 'بازو', 'barbell', 'هالتر', 'عضله دو سر بازویی (بایسپس)', 'ساعد', '۱. هالتر را اندازه عرض شانه بگیرید و با قفل کردن آرنج‌ها میله را تا سینه بالا ببرید.', '/gifs/0031.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_ez_bar_curl', 'جلو بازو با میله خم EZ', 'EZ-Bar Bicep Curl', 'arms', 'بازو', 'barbell', 'هالتر', 'جلو بازو و کاهش فشار روی مچ دست', 'براکیالیس', '۱. روی خمش‌های میله EZ دست بگذارید و با انقباض کامل بالا بیاورید.', '/gifs/0040.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_incline_dumbbell_curl', 'جلو بازو دمبل روی میز شیبدار', 'Incline Dumbbell Curl', 'arms', 'بازو', 'dumbbell', 'دمبل', 'سر بلند عضله جلو بازو (پیک بایسپس)', 'ساعد', '۱. روی نیمکت شیبدار تکیه دهید و دست‌ها را در حالت آویزان جمع کنید.', '/gifs/0315.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_dumbbell_hammer_curl', 'جلو بازو دمبل چکشی', 'Dumbbell Hammer Curl', 'arms', 'بازو', 'dumbbell', 'دمبل', 'عضله براکیورادیالیس و ضخامت بازو و ساعد', 'بایسپس', '۱. دمبل‌ها را به حالت عمودی (کف دست رو به هم) به سمت شانه بالا بکشید.', '/gifs/0313.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_preacher_curl', 'جلو بازو لاری با میله EZ', 'EZ-Bar Preacher Curl', 'arms', 'بازو', 'barbell', 'هالتر', 'ایزولاسیون کامل بخش پایینی جلو بازو', 'ساعد', '۱. بازوها را روی بالشتک میز لاری قرار داده و با تمرکز بالا ببرید.', '/gifs/0070.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_cable_bicep_curl', 'جلو بازو با سیم‌کش ایستاده', 'Standing Cable Bicep Curl', 'arms', 'بازو', 'cable', 'سیم‌کش', 'تنش یکنواخت در تمام طول دامنه جلو بازو', 'ساعد', '۱. دسته سیم‌کش را گرفته و با آرنج ثابت به سمت چانه جمع کنید.', '/gifs/0868.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_triceps_rope_pushdown', 'پشت بازو سیم‌کش با طناب', 'Triceps Rope Pushdown', 'arms', 'بازو', 'cable', 'سیم‌کش', 'سر خارجی و میانی عضله سه سر بازویی', 'ساعد', '۱. طناب را گرفته و در انتهای پایین کشیدن، دو سر طناب را از هم باز کنید.', '/gifs/0241.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_triceps_bar_pushdown', 'پشت بازو سیم‌کش با میله صاف', 'Triceps Straight-Bar Pushdown', 'arms', 'بازو', 'cable', 'سیم‌کش', 'عضله سه سر بازویی (پشت بازو)', 'مچ دست', '۱. با حفظ آرنج‌ها در کنار بدن میله را به سمت پایین صاف کنید.', '/gifs/0240.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_skull_crusher', 'پشت بازو هالتر خوابیده (جمجمه‌شکن)', 'Barbell Skull Crusher', 'arms', 'بازو', 'barbell', 'هالتر', 'سر بلند و میانی پشت بازو', 'مفصل آرنج', '۱. روی نیمکت خوابیده و میله را با خم کردن آرنج‌ها تا بالای پیشانی بیاورید.', '/gifs/0060.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_overhead_dumbbell_triceps', 'پشت بازو دمبل تک جفت‌دست از پشت سر', 'Overhead Dumbbell Triceps Extension', 'arms', 'بازو', 'dumbbell', 'دمبل', 'کشش عمیق سر بلند پشت بازو', 'شانه', '۱. دمبل را با دو دست پشت سر نگه داشته و با باز کردن آرنج‌ها بالا ببرید.', '/gifs/0400.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_parallel_bar_triceps_dip', 'دیپ پارالل عمودی (پشت بازو)', 'Parallel Bar Triceps Dip', 'arms', 'بازو', 'bodyweight', 'وزن بدن', 'پشت بازو و قدرت پرسی', 'سینه، سرشانه', '۱. بدن را کاملاً عمود نگه دارید و با خم کردن آرنج‌ها پایین بروید.', '/gifs/0140.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_dumbbell_kickback', 'پشت بازو دمبل کیک‌بک', 'Dumbbell Triceps Kickback', 'arms', 'بازو', 'dumbbell', 'دمبل', 'انقباض قله پشت بازو', 'دلتوئید خلفی', '۱. تنه را خم کرده و دمبل را به سمت عقب با صاف کردن دست پرتاب کنید.', '/gifs/0328.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_barbell_wrist_curl', 'ساعد مچ با هالتر نشسته', 'Barbell Wrist Curl', 'arms', 'بازو', 'barbell', 'هالتر', 'عضلات خم‌کننده مچ و ساعد', 'پنجه دست', '۱. ساعدها را روی ران قرار داده و هالتر را با مچ‌ها به بالا خم کنید.', '/gifs/0125.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_hanging_leg_raise', 'زیر شکم خلبانی آویزان از بارفیکس', 'Hanging Leg Raise', 'core', 'شکم و میان‌تنه', 'bodyweight', 'وزن بدن', 'بخش تحتانی عضلات شکم و فلکسورهای لگن', 'ساعد، عضلات شانه', '۱. از بارفیکس آویزان شده و بدون تاب پاها را تا زاویه ۹۰ درجه بالا بیاورید.', '/gifs/0472.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_forearm_plank', 'پلانک روی آرنج', 'Forearm Plank', 'core', 'شکم و میان‌تنه', 'bodyweight', 'وزن بدن', 'عضله عرضی شکم و ثبات کل بدن', 'فیله کمر، باسن', '۱. بدن را در یک خط افقی صاف روی آرنج‌ها و پنجه پا قفل و منقبض نگه دارید.', '/gifs/0630.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_floor_crunch', 'کرانچ شکم کلاسیک روی زمین', 'Standard Floor Crunch', 'core', 'شکم و میان‌تنه', 'bodyweight', 'وزن بدن', 'بخش بالایی عضلات ۶ تکه شکم (Rectus Abdominis)', 'میان‌تنه', '۱. زانوها را خم کرده و با انقباض شکم، تیغه‌های شانه را از زمین بلند کنید.', '/gifs/0274.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_kneeling_cable_crunch', 'کرانچ شکم با طناب سیم‌کش (سجده‌ای)', 'Kneeling Cable Crunch', 'core', 'شکم و میان‌تنه', 'cable', 'سیم‌کش', 'افزایش حجم و عمق عضلات شکم با وزنه', 'پهلوها', '۱. زانو بزنید و طناب را کنار سر مهار کرده و با جمع کردن ستون فقرات خم شوید.', '/gifs/0221.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_russian_twist', 'چرخش روسی (راشن توئیست)', 'Russian Twist', 'core', 'شکم و میان‌تنه', 'bodyweight', 'وزن بدن', 'عضلات مورب شکمی (پهلوها)', 'عضله راست شکمی', '۱. در حالت V بنشینید و بالاتنه را به صورت متناوب به چپ و راست بچرخانید.', '/gifs/0687.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_ab_wheel_rollout', 'رول‌اوت شکم با چرخ تمرین (Ab Wheel)', 'Ab Wheel Rollout', 'core', 'شکم و میان‌تنه', 'bodyweight', 'وزن بدن', 'کل زنجیره قدامی شکم و میان‌تنه ضد اکستنشن', 'سرشانه، زیربغل', '۱. زانو زده و چرخ را تا کشش کامل به جلو برانید و با انقباض شکم بازگردید.', '/gifs/0001.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_cable_woodchopper', 'هیزم‌شکن چرخشی با سیم‌کش', 'Cable Woodchopper', 'core', 'شکم و میان‌تنه', 'cable', 'سیم‌کش', 'قدرت چرخشی پهلوها و هسته بدن', 'سرشانه', '۱. دسته سیم‌کش را با چرخش تنه از بالا به سمت زانوی مخالف هدایت کنید.', '/gifs/0245.gif');
INSERT INTO exercises (id, name_fa, name_en, category, category_fa, equipment, equipment_fa, target_muscles, secondary_muscles, instructions_fa, gif_url) VALUES ('ex_air_bike', 'کرانچ دوچرخه (بایسیکل کرانچ)', 'Air Bike Crunch', 'core', 'شکم و میان‌تنه', 'bodyweight', 'وزن بدن', 'درگیری همزمان شکم و پهلوها', 'فلکسور ران', '۱. روی کمر خوابیده و آرنج مخالف را به سمت زانوی مخالف هدایت کنید.', '/gifs/0003.gif');
