"""Generate src/frontend/bodyPaths.ts from MuscleMap's SVG path data.

Source: melihcolpan/MuscleMap (MIT, see NOTICE.md). MuscleMap ships its
outlines as Swift string literals; this extracts the male front/back paths
into a TypeScript module. Sub-group shapes (upper-chest, inner-quad, ...) are
dropped because they overlap their parent muscle.
"""

import json
import re
import urllib.request

MUSCLEMAP_SHA = "7dc03071e03052e8bd4f6351e9176994cd28aa7d"
BASE_URL = f"https://raw.githubusercontent.com/melihcolpan/MuscleMap/{MUSCLEMAP_SHA}/Sources/MuscleMap/Data"

VIEWS = {
    "front": ("MaleFrontPaths.swift", "0 95 727 1280"),
    "back": ("MaleBackPaths.swift", "718 95 727 1280"),
}

# Swift enum case -> slug used by migrations/0004 (muscles_primary/secondary)
SLUGS = {
    "abs": "abs", "adductors": "adductors", "biceps": "biceps", "calves": "calves",
    "chest": "chest", "deltoids": "deltoids", "forearm": "forearm", "gluteal": "gluteal",
    "hamstring": "hamstring", "hipFlexors": "hip-flexors", "lowerBack": "lower-back",
    "obliques": "obliques", "quadriceps": "quadriceps", "serratus": "serratus",
    "tibialis": "tibialis", "trapezius": "trapezius", "triceps": "triceps",
    "upperBack": "upper-back",
}
# Drawn as neutral body outline, never coloured
OUTLINE = {"head", "hair", "neck", "hands", "feet", "knees", "ankles"}
SUBGROUPS = {"frontDeltoid", "rearDeltoid", "innerQuad", "outerQuad", "upperAbs", "lowerAbs",
             "upperChest", "lowerChest", "upperTrapezius", "lowerTrapezius"}

BLOCK_RE = re.compile(r"BodyPartPathData\(\s*slug:\s*\.(\w+)(.*?)\n\s{8}\)", re.S)
STRING_RE = re.compile(r'"([^"]+)"')


def parse(swift_source):
    muscles, outline = {}, []
    for case, body in BLOCK_RE.findall(swift_source):
        paths = STRING_RE.findall(body)
        if case in SUBGROUPS:
            continue
        if case in OUTLINE:
            outline.extend(paths)
        elif case in SLUGS:
            muscles.setdefault(SLUGS[case], []).extend(paths)
        else:
            raise SystemExit(f"Unknown MuscleMap slug: {case}")
    return muscles, outline


def main():
    data = {}
    for view, (filename, view_box) in VIEWS.items():
        with urllib.request.urlopen(f"{BASE_URL}/{filename}") as res:
            muscles, outline = parse(res.read().decode("utf-8"))
        data[view] = {"viewBox": view_box, "outline": outline, "muscles": muscles}
        print(f"{view}: {len(muscles)} muscles, {sum(map(len, muscles.values()))} paths, {len(outline)} outline paths")

    with open("src/frontend/bodyPaths.ts", "w", encoding="utf-8") as f:
        f.write("// Generated by scripts/build_body_paths.py — do not edit by hand.\n")
        f.write(f"// Muscle outlines from melihcolpan/MuscleMap @ {MUSCLEMAP_SHA} (MIT, see NOTICE.md).\n\n")
        f.write("export interface BodyView {\n  viewBox: string;\n  outline: string[];\n  muscles: Record<string, string[]>;\n}\n\n")
        f.write("export const BODY_PATHS: { front: BodyView; back: BodyView } = ")
        f.write(json.dumps(data, separators=(",", ":")))
        f.write(";\n")
    print("Wrote src/frontend/bodyPaths.ts")


if __name__ == "__main__":
    main()
